### PR TITLE
Add support for releases endpoint

### LINKED ISSUE #125: Releases Endpoint
https://www.pivotaltracker.com/help/api/rest/v5#Releases

Currently there is no support for the `releases` endpoint.  This endpoint is useful for obtaining all the stories related to particular release

### PR DESCRIPTION
**Pull request by bmulvihill**
Closes #125 

Adds support for `/releases`
https://www.pivotaltracker.com/help/api/rest/v5#Releases

One caveat is I am unsure how to get the test data for VCR to write the tests.

### CODE REVIEW

**Comment by forest** [comment]
@bmulvihill for releases you can will want to add a test for `Stories#get_release` and `Project#releases`. I think it makes sense to add the tests to the respective test files that already exist. You will see from the existing tests, like for `Story#tasks` that `VCR.use_cassette` is used to wrap the parts that make API calls. https://github.com/dashofcode/tracker_api/blob/master/test/story_test.rb#L212

VCR will record the API call and save the response. Then in subsequent test runs it will return this saved response instead of actually making the API call. To get VCR to re-record the response just delete the file with the response and it will be recreated.

When you are happy with the reponse add it to git.

**Comment by bmulvihill** [comment]
@forest I guess my main question with the tests were which project board you using to create the test data?

**Comment by bmulvihill** [comment]
Just answered my own question :)
https://github.com/dashofcode/tracker_api/blob/master/test/minitest_helper.rb#L19-L31

**Comment by forest** [comment]
Ah. The project has three for different use cases but I typically use #1.
https://github.com/dashofcode/tracker_api/blob/master/test/minitest_helper.rb#L28

You might have to login and create from releases so you have some data to query.

**Comment by forest** [comment]
👍  Looks good.

**Pull request merged**
