### PR TITLE
update an existing story with new labels

### PR DESCRIPTION
**Pull request by manojpm**

### CODE REVIEW

**Comment by forest** [comment]
@manojpm thanks for the pull request.

I need to think about this a bit more. I don't really want to add a specific method for this. I'd like to use the existing update functionality. Maybe something like:

```
story.labels << 'new-label'
story.save
```

**Comment by manojpm** [comment]
I also thought about this. When we do  story.labels << 'new-label',  labels does not get marked as dirty. So nothing to update.   The other problem I see is that the stories PUT method takes an array of name/value pair for updating the labels.  https://www.pivotaltracker.com/help/api/rest/v5#projects_project_id_stories_story_id_put

**Comment by forest** [comment]
I think this will work for making the API request happy.
```
story.labels << Label.new(name: 'my-special-label')
```
We could also make labels be our own collection class and then override the `<<` operator. Then we can be smart about accepting single or multiple stings and even `Label` objects or hashes to add to the collection. See this documentation for Virtus (https://github.com/solnic/virtus#important-note-about-member-coercions) on how to make a special `BookCollection` and how to use it.

That might also solve the dirty tracking problem, but not sure.

**Comment by manojpm** [comment]
Thanks for the suggestions. BTW, we will have to override other array methods as well ? 
For example,  you want to delete a label from the story, then you call the Array#delete_at, Array#delete_if etc.

**Comment by forest** [comment]
It might be better to use composition instead of inheriting from `Array`. Then we can just implement `add`, `delete`, and `<<` on the collection class and have an internal array to hold the data.

**Comment by forest** [comment]
@manojpm I finally got around to supporting adding new Labels to a Story.

See this pull request: https://github.com/dashofcode/tracker_api/pull/48
Commit: https://github.com/dashofcode/tracker_api/commit/f299fbb9ef7b0d1174f3c3fe7e090ace6c88f385

I'm going to close this pull now.

**Pull request closed without merging**
