### PR TITLE
Properly support bundler 2

### PR DESCRIPTION
**Pull request by shanecav84**
Fixes incorrect versioning introduced in #132

### CODE REVIEW

**Comment by shanecav84** [comment]
@forest Can you turn on builds for PRs?

**Comment by forest** [comment]
@shanecav84 it should be. I just looked at the settings and it has pull requests on. Please try again.

**Comment by forest** [comment]
@shanecav84 I don't know why it isn't getting triggered. I'll try removing the integration and adding it again.

**Comment by forest** [comment]
@shanecav84 I don't know why builds are not triggering on Travis CI. They are in the middle of a migration from .org to .com for opensource. Maybe that is the readon. For now I'm just going to merge and trigger a build manually.

**Pull request merged**
