### PR TITLE
Verify story owners can be changed via tests

### PR DESCRIPTION
**Pull request by forest**

### CODE REVIEW

**Comment by forest** [comment]
@drselump14 I pulled your branch and added tests to make sure you can update story owners via the owner_ids setter.

Because of dirty tracking, you need to use the setter `owner_ids=`. You can't manipulate the array via typical array methods like `<<` or `push`. That might have been your issue before.

It should work now with the latest code. You can see I just commented out your code and added tests.

**Comment by drselump14** [comment]
Thanks @forest ..
Is there any hope that  `<<`  and `push` method can be implemented? 
That would be more convenient when adding new owner to existing owners list

**Comment by forest** [comment]
Agreed. I spend a few hours on that when I first added dirty tracking. I was getting really hacky because it meant monkey more patching Array methods. I even tried creating my own list object to encapsulate that functionality, but it didn't work. I forget why exactly. In the end, I just punted on it and put a note in the readme. Maybe some day I'll try again, or someone else can take a crack at it.

**Comment by drselump14** [comment]
Why we don't just implement the `<<`  and `push` using pivotal tracker POST owner apis like I proposed before? Maybe we don't need to monkey patch the Array method, just implement a new class that inherits the Array class.

What do you think?

**Pull request merged**
