### PR TITLE
Add epic creation and update

### PR DESCRIPTION
**Pull request by erbunao**
We added a few changes to be able to create an epic or update an existing one. We followed the implementations of how a story is created or updated.

### CODE REVIEW

**Comment by forest** [comment]
:+1: Thanks for the contribution.

**Comment by rpechayr** [comment]
Any ETA for the new version of the gem including this change ?

**Comment by forest** [comment]
@rpechayr I thought I had released this already. Sorry.

I'll try to get a new version up today.

**Comment by rpechayr** [comment]
Thanks !

**Pull request merged**
