### PR TITLE
Dirty tracking

### PR DESCRIPTION
**Pull request by forest**
Addresses #62 while keeping the `Story#save` interface.

  * Added benefit of only sending the changed attributes. Meaning less data transfer.

### CODE REVIEW

**Comment by sbleon** [comment]
@forest this is awesome! Thanks so much!

**Comment by sbleon** [comment]
Awesome job, @forest! Thanks for working so hard on this!

**Comment by sbleon** [comment]
I tested your branch on my project (with a very simple test) and it worked as expected.

**Comment by forest** [comment]
Great. Thanks for the feedback and reviewing the changes. I'll get this released.

My goal is to put some of the foundational things in place and keep the code easy to understand so many people can contribute. The majority of my use cases are reading data, so I'm happy to have the help on update features.

**Pull request merged**
