### PR TITLE
Add ability to update tasks

### PR DESCRIPTION
**Pull request by cap10morgan**
This adds the ability to update tasks. I'm using it to mark tasks as complete.

### CODE REVIEW

**Comment by cap10morgan** [comment]
I can't tell what went wrong with that JRuby build.

**Comment by forest** [comment]
@cap10morgan thanks for the contribution. The JRuby build is fickle. Might resolve itself in the next run, if not I'll dig into it.

**Comment by cap10morgan** [comment]
Cool, thanks for the merge! Do you know when this will go out in a new release?

**Comment by forest** [comment]
I'll try to publish a release early next week. Even if this is the only
thing.

**Comment by forest** [comment]
@cap10morgan v1.1.0 released.

**Comment by cap10morgan** [comment]
Awesome, thanks!

**Pull request merged**
