### PR TITLE
Adding my activity endpoint

### PR DESCRIPTION
**Pull request by fvioz**

### CODE REVIEW

**Comment by forest** [comment]
@fvioz thanks for the pull request. There have been 4 for adding activity, so will be taking the best from all to get this in the next release.

**Comment by fvioz** [comment]
@forest yep I noticed that this morning you merge the code for story activity, I merged that only name that method. If you need some changes to merge it, any suggestions are welcome.

**Comment by forest** [comment]
@fvioz I got the basic project Activity code merged in. You also added PromaryResource which I don't have in yet. If you want that, can you rebase and get that working with the latest code?

**Comment by fvioz** [comment]
@forest done

**Comment by forest** [comment]
@fvioz thanks. I'm going to refactor the interface a bit to be consistent with notifications.

```
client.activity
```

**Pull request merged**
