### PR TITLE
Handle non-JSON responses

### LINKED ISSUE #117: A TrackerApi::Error occurred in background at 2016-01-20 08:47
```ruby
 A TrackerApi::Error occurred in background at 2016-01-20 08:47 757: unexpected token at '<h1>This website is under heavy load</h1><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/client.rb:207:in `rescue in request'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/client.rb:187:in `request'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/client.rb:57:in `get'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/endpoints/story.rb:11:in `get'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/resources/project.rb:141:in `story'
  /app/app/services/pivotal/price_tags/project_updater.rb:127:in `update_story'
```

This is the same error noted in Issue #61. It's actually a `JSON::Parser` error. I'll try to get a PR to handle it by the end of the week.

### PR DESCRIPTION
**Pull request by patientdev**
The `TrackerApi::Error` in #61 is due to a `Faraday::Error::ParsingError`. The default error message for an overloaded server for Pivotal Tracker's app server, Phusion Passenger, is an HTML response with a 503 status code. `TrackerApi::Client` was expecting all responses to be JSON, and so passed each response to the JSON parser of `Faraday::ResponseMiddleware`, which raised the `ParsingError`. This is fixed by only passing JSON-related content-types to the middleware parser. Faraday will handle other responses normally; e.g. raising a `ServerError` for overloaded server responses. Closes #117.

In the course of sorting that out, I found that responses to attachment uploads also return `text/html`, which would again raise a `ParsingError`. This response is intentional as noted in the commit body for 
6038ba8. This is fixed by setting our request's `Accept` header to `application/json`.

### CODE REVIEW

**Comment by forest** [comment]
+1

**Comment by shanecav84** [comment]
@forest Could you cut a release for this?

**Comment by forest** [comment]
@shanecav84 done.

**Comment by shanecav84** [comment]
Thanks!

**Pull request merged**
