### PR TITLE
Initial implementation of #create_workspace

### PR DESCRIPTION
**Pull request by mscharley**
Hey guys,

We needed a `#create_workspace` method, so here it is.

### CODE REVIEW

**Comment by forest** [comment]
Sorry it took me awhile to get to this. Looks good. Thanks.

**Comment by mscharley** [comment]
Hi @forest,

Thanks for that. Just for my info, how long do you expect before this lands in a release?

**Comment by forest** [comment]
I'll get a new release out this week.

**Comment by mscharley** [comment]
That'd be amazing, thanks.

**Comment by forest** [comment]
@mscharley released v1.4.0

**Pull request merged**
