### PR TITLE
add story#add_owner method using owner's API

### PR DESCRIPTION
**Pull request by drselump14**
somehow I couldn't add owner using  self.owners= method, so I add add_owner method using owner's API 

+ add attribute person for Comment model, because it's needed to get person object directly from comment

### CODE REVIEW

**Comment by forest** [comment]
@drselump14 you can add to the array of `owner_ids` and that will get save with the story is saved. See https://github.com/dashofcode/tracker_api/pull/88/files#diff-7801f5012a085139832e168522bc85dcL55. 

You should need to add the new endpoint.

If you want the `story.owners=` to work you can override and update the `owner_ids`. Make sure you have the current list of owners or owner_ids so you don't overwrite existing owners.

**Comment by drselump14** [comment]
@forest Thanks for the reply.
I've tried the owner_ids= method before, but sometimes it didn't work as expected. I don't know how to replicate the bug. Maybe that's the reason why they provide API for posting owners.

'You should need to add the new endpoint.' 
Could you please explain more about this point please? I think story_owners endpoint is fit with this function.

**Comment by forest** [comment]
I'll take a look. If there is a bug with owner_ids it would be good to fix
that. Having multiple ways to do the same this isn't ideal unless there is
good reason.

Your solution might be the right one.

**Comment by drselump14** [comment]
You're right , i agree with you.

**Comment by forest** [comment]
This is not needed. Just use `owner_ids=`.

`story.owner_ids = [123, 456]`

**Pull request closed without merging**
