### PR TITLE
Added feature to add members to projects

### PR DESCRIPTION
**Pull request by newOnahtaN**
Ran into needing this, thought you might find it useful!!

### CODE REVIEW

**Comment by newOnahtaN** [comment]
Ran into needing this, thought you might find it useful!

**Comment by forest** [comment]
Thanks for the pull. I'll try to get to this early next week.

**Comment by forest** [comment]
:+1: Thanks for the contribution.

**Comment by newOnahtaN** [comment]
Fantastic! Thanks.

**Pull request merged**
